import {
  Baby,
  Beer,
  Bike,
  Bitcoin,
  BookOpen,
  Briefcase,
  Building2,
  Bus,
  Car,
  ChartColumn,
  ChartLine,
  CircleHelp,
  Coffee,
  Coins,
  CreditCard,
  Droplets,
  Dumbbell,
  Film,
  Fuel,
  Gamepad2,
  Gem,
  Gift,
  GraduationCap,
  HandCoins,
  HandHeart,
  Heart,
  HeartPulse,
  House,
  Landmark,
  Laptop,
  Music,
  Package,
  PawPrint,
  Percent,
  PiggyBank,
  Pill,
  Plane,
  Receipt,
  Repeat,
  RotateCcw,
  Scale,
  Scissors,
  Shield,
  Shirt,
  ShoppingBag,
  ShoppingCart,
  Smartphone,
  Sofa,
  Sparkles,
  Stethoscope,
  TrainFront,
  TreePalm,
  TrendingUp,
  Tv,
  Umbrella,
  Utensils,
  Wallet,
  Wifi,
  Wine,
  Wrench,
  Zap,
  type LucideIcon,
} from 'lucide-react';

/** Icônes proposées pour les catégories et les comptes. */
export const ICONS: Record<string, LucideIcon> = {
  house: House,
  'shopping-cart': ShoppingCart,
  utensils: Utensils,
  coffee: Coffee,
  wine: Wine,
  beer: Beer,
  car: Car,
  fuel: Fuel,
  bus: Bus,
  'train-front': TrainFront,
  bike: Bike,
  plane: Plane,
  'tree-palm': TreePalm,
  'heart-pulse': HeartPulse,
  stethoscope: Stethoscope,
  pill: Pill,
  shield: Shield,
  umbrella: Umbrella,
  zap: Zap,
  droplets: Droplets,
  wifi: Wifi,
  smartphone: Smartphone,
  tv: Tv,
  laptop: Laptop,
  repeat: Repeat,
  'shopping-bag': ShoppingBag,
  shirt: Shirt,
  scissors: Scissors,
  sofa: Sofa,
  wrench: Wrench,
  gift: Gift,
  'hand-heart': HandHeart,
  heart: Heart,
  'gamepad-2': Gamepad2,
  film: Film,
  music: Music,
  'book-open': BookOpen,
  dumbbell: Dumbbell,
  'graduation-cap': GraduationCap,
  baby: Baby,
  'paw-print': PawPrint,
  landmark: Landmark,
  receipt: Receipt,
  'credit-card': CreditCard,
  package: Package,
  briefcase: Briefcase,
  sparkles: Sparkles,
  'rotate-ccw': RotateCcw,
  'hand-coins': HandCoins,
  percent: Percent,
  coins: Coins,
  'piggy-bank': PiggyBank,
  'trending-up': TrendingUp,
  wallet: Wallet,
  'chart-line': ChartLine,
  'chart-column': ChartColumn,
  bitcoin: Bitcoin,
  'building-2': Building2,
  gem: Gem,
  scale: Scale,
};

export const ICON_NAMES = Object.keys(ICONS);

export function getIcon(name: string | undefined): LucideIcon {
  return (name && ICONS[name]) || CircleHelp;
}
